# -*- coding: utf-8 -*-
"""Копия блокнота "Копия блокнота "Untitled0.ipynb""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyHBZu-zDvcgb29MkXft7KPQoVamvXrG
"""

import sqlite3, pandas as pd, os

db_file = 'shop.db'
if os.path.exists(db_file):
    os.remove(db_file)

conn = sqlite3.connect(db_file)
cur = conn.cursor()

cur.executescript('''
    CREATE TABLE products (
        product_id INTEGER PRIMARY KEY,
        product_name TEXT,
        category TEXT
    );
    CREATE TABLE prices (
        price_id INTEGER PRIMARY KEY,
        product_id INTEGER,
        price REAL,
        recorded_at TEXT,
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    );
''')

products = [
    (1, 'Молоко', 'Молочные'), (2, 'Хлеб', 'Хлебобулочные'),
    (3, 'Яблоки', 'Фрукты'), (4, 'Сыр', 'Молочные'),
    (5, 'Кофе', 'Напитки'), (6, 'Чай', 'Напитки'),
    (7, 'Масло', 'Молочные'), (8, 'Бананы', 'Фрукты')
]

prices = [
    (1,1,89.90,'2024-01-01'), (2,1,92.50,'2024-01-15'), (3,1,87.00,'2024-02-01'),
    (4,2,45.00,'2024-01-01'), (5,2,47.50,'2024-01-15'), (6,2,44.00,'2024-02-01'),
    (7,3,120.00,'2024-01-01'), (8,3,115.50,'2024-01-15'), (9,3,130.00,'2024-02-01'),
    (10,4,450.00,'2024-01-01'), (11,4,475.00,'2024-01-15'), (12,4,440.00,'2024-02-01'),
    (13,5,650.00,'2024-01-01'), (14,5,680.00,'2024-01-15'), (15,5,630.00,'2024-02-01'),
    (16,6,250.00,'2024-01-01'), (17,6,245.00,'2024-01-15'), (18,6,260.00,'2024-02-01'),
    (19,7,180.00,'2024-01-01'), (20,7,195.00,'2024-01-15'), (21,7,175.00,'2024-02-01'),
    (22,8,90.00,'2024-01-01'), (23,8,88.50,'2024-01-15'), (24,8,95.00,'2024-02-01')
]

cur.executemany('INSERT INTO products VALUES (?, ?, ?)', products)
cur.executemany('INSERT INTO prices VALUES (?, ?, ?, ?)', prices)
conn.commit()
print(" База 'shop.db' создана: 8 товаров, 24 записи о ценах")

import pandas as pd, sqlite3
conn = sqlite3.connect('shop.db')
df = pd.read_sql("SELECT price FROM prices", conn)
conn.close()

result = pd.DataFrame({
    'Показатель': [
        'Среднее значение',
        'Медиана',
        'Стандартное отклонение',
        'Минимальная цена',
        'Максимальная цена'
    ],
    'Значение': [
        f"{df['price'].mean():.2f} руб.",
        f"{df['price'].median():.2f} руб.",
        f"{df['price'].std():.2f} руб.",
        f"{df['price'].min():.2f} руб.",
        f"{df['price'].max():.2f} руб."
    ]
})

print(result.to_string(index=False))

import pandas as pd, sqlite3
conn = sqlite3.connect('shop.db')
df = pd.read_sql("""
    SELECT p.product_name, p.category, pr.price
    FROM prices pr
    JOIN products p ON pr.product_id = p.product_id
""", conn)
conn.close()

q1 = df['price'].quantile(0.25)
q2 = df['price'].quantile(0.50)
q3 = df['price'].quantile(0.75)
iqr = q3 - q1

above_q3 = df[df['price'] > q3][['product_name', 'category', 'price']].sort_values('price', ascending=False)


quartiles_table = pd.DataFrame({
    'Показатель': ['Q1 (25-й процентиль)', 'Q2 (медиана, 50%)', 'Q3 (75-й процентиль)', 'IQR (межквартильный размах)'],
    'Значение': [f"{q1:.2f} руб.", f"{q2:.2f} руб.", f"{q3:.2f} руб.", f"{iqr:.2f} руб."]
})

print(quartiles_table.to_string(index=False))

print("\nТовары с ценой выше Q3".format(q3))
print(f"Количество записей: {len(above_q3)} из {len(df)} ({len(above_q3)/len(df)*100:.1f}%)")
print("Список товаров:")
print(above_q3.to_string(index=False))

import pandas as pd
import sqlite3
conn = sqlite3.connect('shop.db')
df = pd.read_sql("""
    SELECT p.category, pr.price
    FROM prices pr
    JOIN products p ON pr.product_id = p.product_id
""", conn)
conn.close()


by_category = df.groupby('category')['price'].agg(
    count='count',
    avg_price='mean',
    median_price='median',
    std_price='std'
).round(2).sort_values('avg_price', ascending=False).reset_index()

by_category.columns = [
    'Категория',
    'Кол-во записей',
    'Средняя цена (руб.)',
    'Медиана (руб.)',
    'Ст. отклонение (руб.)'
]

print(by_category.to_string(index=False))

import pandas as pd
import sqlite3
conn = sqlite3.connect('shop.db')
df = pd.read_sql("""
    SELECT p.product_name, pr.price
    FROM prices pr
    JOIN products p ON pr.product_id = p.product_id
""", conn)
conn.close()

all_products = df.groupby('product_name')['price'].agg(
    min_p='min',
    max_p='max'
).reset_index()

all_products['Разброс'] = (all_products['max_p'] - all_products['min_p']).round(2)

top5 = all_products.sort_values('Разброс', ascending=False).head(5)

top5.columns = [
    'Товар',
    'Мин. цена (руб.)',
    'Макс. цена (руб.)',
    'Разброс (руб.)'
]

print(top5.to_string(index=False))