# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled1.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcHNoMKViNEXNwzQqeci0-Onm-zpbRLL
"""

import sqlite3
import os

db_file = 'shop.db'
if os.path.exists(db_file):
    os.remove(db_file)

conn = sqlite3.connect(db_file)
cur = conn.cursor()

cur.executescript('''
    CREATE TABLE products (
        product_id INTEGER PRIMARY KEY,
        product_name TEXT,
        category TEXT
    );
    CREATE TABLE prices (
        price_id INTEGER PRIMARY KEY,
        product_id INTEGER,
        price REAL,
        recorded_at TEXT,
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    );
''')

products = [
    (1, 'Молоко', 'Молочные'), (2, 'Хлеб', 'Хлебобулочные'),
    (3, 'Яблоки', 'Фрукты'), (4, 'Сыр', 'Молочные'),
    (5, 'Кофе', 'Напитки'), (6, 'Чай', 'Напитки'),
    (7, 'Масло', 'Молочные'), (8, 'Бананы', 'Фрукты')
]

prices = [
    (1,1,89.90,'2024-01-01'), (2,1,92.50,'2024-01-15'), (3,1,87.00,'2024-02-01'),
    (4,2,45.00,'2024-01-01'), (5,2,47.50,'2024-01-15'), (6,2,44.00,'2024-02-01'),
    (7,3,120.00,'2024-01-01'), (8,3,115.50,'2024-01-15'), (9,3,130.00,'2024-02-01'),
    (10,4,450.00,'2024-01-01'), (11,4,475.00,'2024-01-15'), (12,4,440.00,'2024-02-01'),
    (13,5,650.00,'2024-01-01'), (14,5,680.00,'2024-01-15'), (15,5,630.00,'2024-02-01'),
    (16,6,250.00,'2024-01-01'), (17,6,245.00,'2024-01-15'), (18,6,260.00,'2024-02-01'),
    (19,7,180.00,'2024-01-01'), (20,7,195.00,'2024-01-15'), (21,7,175.00,'2024-02-01'),
    (22,8,90.00,'2024-01-01'), (23,8,88.50,'2024-01-15'), (24,8,95.00,'2024-02-01')
]

cur.executemany('INSERT INTO products VALUES (?, ?, ?)', products)
cur.executemany('INSERT INTO prices VALUES (?, ?, ?, ?)', prices)
conn.commit()
conn.close()
print('База shop.db создана')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 10
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'Liberation Sans']
plt.rcParams['axes.unicode_minus'] = False

conn = sqlite3.connect('shop.db')

query = """
    SELECT
        p.product_name,
        p.category,
        pr.price,
        pr.recorded_at
    FROM prices pr
    JOIN products p ON pr.product_id = p.product_id
    ORDER BY pr.recorded_at
"""
df = pd.read_sql(query, conn)
conn.close()

mean_price = df['price'].mean()
median_price = df['price'].median()
q1 = df['price'].quantile(0.25)
q3 = df['price'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

plt.figure(figsize=(12, 7))
sns.boxplot(data=df, x='category', y='price', palette='Set2', showfliers=True)
plt.title('Распределение цен по категориям')
plt.xlabel('Категория')
plt.ylabel('Цена, руб.')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('graph1_general.png', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(12, 7))
sns.histplot(data=df, x='price', bins=15, kde=True, color='skyblue', edgecolor='black')
plt.axvline(mean_price, color='red', linestyle='--', linewidth=2, label=f'Среднее: {mean_price:.0f} руб.')
plt.axvline(median_price, color='green', linestyle='-.', linewidth=2, label=f'Медиана: {median_price:.0f} руб.')
plt.axvline(q1, color='orange', linestyle=':', linewidth=1, label=f'Q1: {q1:.0f} руб.')
plt.axvline(q3, color='orange', linestyle=':', linewidth=1, label=f'Q3: {q3:.0f} руб.')
plt.axvline(lower_bound, color='purple', linestyle=':', linewidth=1, alpha=0.7, label=f'Нижняя граница: {lower_bound:.0f} руб.')
plt.axvline(upper_bound, color='purple', linestyle=':', linewidth=1, alpha=0.7, label=f'Верхняя граница: {upper_bound:.0f} руб.')
plt.title('Распределение цен со статистическими метриками')
plt.xlabel('Цена, руб.')
plt.ylabel('Количество записей')
plt.legend()
plt.tight_layout()
plt.savefig('graph2_with_stats.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"Всего записей: {len(df)}")
print(f"Среднее: {mean_price:.2f} руб.")
print(f"Медиана: {median_price:.2f} руб.")
print(f"Q1: {q1:.2f} руб.")
print(f"Q3: {q3:.2f} руб.")
print(f"IQR: {iqr:.2f} руб.")
print(f"Границы выбросов: [{lower_bound:.2f}; {upper_bound:.2f}] руб.")
anomalies = df[(df['price'] < lower_bound) | (df['price'] > upper_bound)]
print(f"Аномалий обнаружено: {len(anomalies)}")
if len(anomalies) > 0:
    print(anomalies[['product_name', 'category', 'price']].to_string(index=False))

df.to_csv('processed_data.csv', index=False, encoding='utf-8-sig')